### ISSUE TITLE
Fix transform page :bug: 

### ISSUE THREAD

**Issue by mpadge** [mpadge/UrbanAnalyst#106]
It sometimes hangs on "*Calculating ...*". The whole process should be changed so calculation is only triggered by actively clicking the button, rather than automatically on page load. Need to also catch any errors during calculation and handle appropriately.

### TODO

- [x] Only calculate on active button press
- [ ] Catch and handle calculation errors
- [ ] ~~Initial load with map and not mutation data~~

**Comment by mpadge** [comment]
That fixes most issues, but still a couple of minor bugs remaining ...

**Comment by mpadge** [comment]
Re-opening because now the extra layers selection no longer triggers a re-calculation of the transform algorithm.
