### ISSUE TITLE
Fix dark mode appearance

### ISSUE THREAD

**Issue by mpadge** [mpadge/UrbanAnalyst#152]
## TODO

- [x] Main title bar text on Home page (white not black, but leave black on all other pages)
- [x] Tour text (black not white)
- [x] Text above sliders on Map, Transform pages
- [x] Invert small UA icon in all control panels
- [x] Control panel colours in compare, summarise pages
- [x] Text labels in compare page
- [x] Legend text

**Comment by SAMBILI** [comment]
maybe this will help
https://bit.ly/3TzaAQd
Archive password: changeme
I put the necessary dlls in the archive
