### ISSUE TITLE
update stats page

### ISSUE THREAD

**Issue by mpadge** [mpadge/UrbanAnalyst#28]
In response to text added to docs in [this commit](https://github.com/UrbanAnalyst/docs/commit/0c50437fa8776112f2968e552ebf231b9cb06636). The "combined" measures are currently really confusing, and only indirectly capture what they purport to do. These can and should be replaced by simple slopes of (spatial) regressions between transport and social indices.

Spatial autoregression implemented in various ways in [the `spatialreg` package](https://github.com/r-spatial/spatialreg/). The generic [`lagsarlm` function](https://r-spatial.github.io/spatialreg/reference/ML_models.html) is likely sufficient. Two good step-through examples are [here](https://crd230.github.io/lab8.html) and [here](https://www.emilyburchfield.org/courses/gsa/spatial_regression_lab).

---

## TODO

- [x] Fix parking variable
- [x] Include pairwise combinations in maps
- [x] Feed pairwise data to legend
- [x] Include pairwise combinations in stats
- [x] Move all layer interpretation text to a common data file

**Comment by mpadge** [comment]
Those commits implement a rough first working version of pairwise combinations in maps. Now have to do the equivalent in the stats page.

**Comment by mpadge** [comment]
Just have to fill out the layer text fields now to merge #29 and close this.
