### ISSUE TITLE
mutation algorithm

### ISSUE THREAD

**Issue by mpadge** [mpadge/UrbanAnalyst#49]
## TODO

- [x] Integrate rust WASM of [UrbanAnalyst/uamutations](https://github.com/UrbanAnalyst/uamutations)
- [ ] Add "mutate" button to map controls
- [ ] Use button to call mutation algorithm and deliver updated/mutated map

~~The uamutations algorithm can be modified by reading the json data in javascript, and then using the [serde_wasm_bindgen crate](https://docs.rs/serde-wasm-bindgen/latest/serde_wasm_bindgen/) to deserialise the JSON data in rust:~~
``` rust
#[wasm_bindgen]
pub fn receive_json_from_js(val: JsValue) {
    let data: serde_json::Value = serde_wasm_bindgen::from_value(val).unwrap();
    // ... whatever
}
```

Actually the data to be processed in rust are not the reduced map data, but more extensive simply JSON (not geoJSON) arrays, which are entirely processed and aggregated in rust, in order to return a single column which can then be used to replace an existing column of the local geoJSON data using code like https://github.com/mpadge/UrbanAnalyst/issues/47#issuecomment-1825673287. So the WASM routines can start by reading the JSON file directly.

**Comment by mpadge** [comment]
The above commits have add all of the source rust code for the mutation algorithm, but it is not yet called anywhere from `src`.

**Comment by mpadge** [comment]
Closing this now to address remaining tasks as separate issues
